// EN.about.name=About
// EN.about.organization=About organization
// EN.avatar.modal.title=Change user avatar
// EN.button.another.tasks=Other tasks
// EN.button.as.organization=As organization
// EN.button.as.partner=As partner
// EN.button.as.volunteer=As volunteer
// EN.button.attach.document=Attach document
// EN.button.attach.file=Attach file
// EN.button.change.photo=Change photo
// EN.button.create.story=Create success story
// EN.button.delete=Delete
// EN.button.login=LogIn
// EN.button.organization=Nongovermental organization
// EN.button.partner=Partner
// EN.button.register=Sign up
// EN.button.save.changes=Save changes
// EN.button.save=Save changed
// EN.button.upload.photo=Upload photo
// EN.button.upload=Upload
// EN.button.volunteer=Volunteer
// EN.categories.organization=Organization task categories
// EN.category.name=Category
// EN.choose.category=Select a category
// EN.confirmpassword.name=Confirm password
// EN.day.month.year=DD.MM.YYYY
// EN.document.modal.title=Upload new document
// EN.document.upload.invalid=Unsupported document type. Please choose another file
// EN.duration=Duration
// EN.email.name=Email
// EN.first.name=First name
// EN.header.change.lang=Change lang
// EN.header.lang.eng=EN
// EN.header.lang.ru=RU
// EN.header.lang.ua=UA
// EN.invalidCredentials=Invalid credentials!
// EN.label.about.project=About project
// EN.label.about.us=About us
// EN.label.can.upload=You can upload up to
// EN.label.cancel=Cancel
// EN.label.choose.all=Choose all
// EN.label.completed.tasks=Completed tasks
// EN.label.confirm.action=Confirm action
// EN.label.confirm=Confirm
// EN.label.contact.us=Contact us
// EN.label.contacts=Contacts
// EN.label.currency.RUB.name=rubles
// EN.label.currency.RUB=\u20BD
// EN.label.currency.UAH.name=hryvnia
// EN.label.currency.UAH=\u20B4
// EN.label.currency.USD.name=dollars
// EN.label.currency.USD=\u0024
// EN.label.date.date.completed=Date of completion
// EN.label.draft.tasks=Drafts
// EN.label.duration.measure.DAY.name=days
// EN.label.duration.measure.DAY=Days
// EN.label.duration.measure.WEEK.name=weeks
// EN.label.duration.measure.WEEK=Weeks
// EN.label.enter=Enter
// EN.label.forgotPassword=Forgot Password?
// EN.label.help=Help
// EN.label.inprogress.tasks=In progress tasks
// EN.label.invite=Invite
// EN.label.login=Login
// EN.label.main=Main
// EN.label.members=Members
// EN.label.news=News
// EN.label.no.completed.tasks=You don't have completed tasks yet
// EN.label.no.draft.tasks=You don't have draft tasks yet
// EN.label.no.inprogress.tasks=You don't have in progress tasks yet
// EN.label.no.published.tasks=You don't have published tasks yet
// EN.label.on.site.since=On site since
// EN.label.organizations=Organizations
// EN.label.partners=Partners
// EN.label.password=Password
// EN.label.performers=Performers
// EN.label.photo=photo(s)
// EN.label.potential.performers=Potential performers
// EN.label.published.tasks=Published tasks
// EN.label.registration.as=You're registering as
// EN.label.registration=Registration
// EN.label.remove.from.task=Remove from task
// EN.label.respond=Respond
// EN.label.responded=Responded
// EN.label.rules=Rules
// EN.label.save.for.ngo=Saved for NGO
// EN.label.search.results.tasks=task(s)
// EN.label.search.results=Search results
// EN.label.search.tasks.partner=For partners
// EN.label.search.tasks.volunteer=For volunteers
// EN.label.show.more=Show more
// EN.label.sort.by=Sort by
// EN.label.task.categories=Categories
// EN.label.task.duration.LONG_TERM=Long term
// EN.label.task.duration.UP_TO_MONTH=Up to month
// EN.label.task.duration.UP_TO_TWO_WEEKS=Up to two weeks
// EN.label.task.duration.UP_TO_WEEK=Up to week
// EN.label.task.duration=Task duration
// EN.label.task.status.ALL=All tasks
// EN.label.task.status.COMPLETED=Completed
// EN.label.task.status.IN_PROGRESS=In progress
// EN.label.task.status.NEW=New
// EN.label.task.status.PUBLISHED=Published
// EN.label.task.status.URGENT=Urgent
// EN.label.task.status=Task status
// EN.label.tasks.completed=Completed
// EN.label.tasks.draft=Drafts
// EN.label.tasks.in_progress=In progress
// EN.label.tasks.published=Published
// EN.label.tasks.search=Tasks search
// EN.label.tasks=Tasks
// EN.label.title.organization.representatives=Organization representatives
// EN.label.title.volunteers=Volunteers
// EN.label.volunteers=Volunteers
// EN.label.works.in.categories=Works in categories
// EN.last.name=Last name
// EN.link.register=Don't have account? To register it
// EN.linkedin.name=Link to LinkedIn:
// EN.linkedin.url=LinkedIn link
// EN.logo.modal.title=Upload new logo
// EN.logo.upload.invalid=Unsupported logo type. Please choose another file
// EN.logoutSuccess=You have been logged out.
// EN.messages.account.settings.update.success=Account settings have been successfully updated
// EN.messages.avatar.upload.failure=Error during avatar image uploading. Please try again later
// EN.messages.avatar.upload.success=New avatar image has been successfully uploaded
// EN.messages.error.something.went.wrong=Oops! Something went wrong!
// EN.messages.error.try.again=Try do it again or to message for us.
// EN.messages.organization.data.update.success=Organization data has been successfully updated
// EN.messages.organization.document.delete.failure=Error during document deletion. Please try again later
// EN.messages.organization.document.delete.success=Document has been successfully deleted
// EN.messages.organization.document.update.success=New document has been successfully uploaded
// EN.messages.organization.logo.delete.failure=Error during logo image deletion. Please try again later
// EN.messages.organization.logo.delete.success=Logo image has been successfully deleted
// EN.messages.organization.logo.update.success=New logo image has been successfully uploaded
// EN.messages.story.edit.success=Success story has been successfully updated. Please, wait for the administration approval.
// EN.messages.story.photo.delete.failure=Error while deleting photo. Please try again later
// EN.messages.story.photo.delete.success=Photo has been successfully deleted
// EN.messages.story.photo.upload.fail=Incorrect type and/or size of the photo. Please chose another one.
// EN.messages.story.photo.upload.success=New photo has been successfully uploaded
// EN.messages.story.registration.success=New success story has been successfully registered. Please, wait for the administration approval.
// EN.messages.task.edit.not.allowed=You cannot edit already published task!
// EN.messages.task.edit.success=Task has been successfully edited.
// EN.messages.task.registration.success=New task has been successfully registered. Please, wait the administration approval.
// EN.messages.task.respond.confirm.failure=Something went wrong. Maybe this performer is already confirmed?
// EN.messages.task.respond.confirm.success=You successfully confirmed new performer for this task.
// EN.messages.task.respond.confirm=Are you sure you want to respond to this task?
// EN.messages.task.respond.confirmation.confirm=Are you sure you want to confirm given responded user?
// EN.messages.task.respond.failure=Something went wrong. Maybe you already responded to this task?
// EN.messages.task.respond.success=You successfully responded to this task. Wait for the author respond.
// EN.messages.tasks.stages.add.fail=You cannot add more stages for this task
// EN.messages.user.data.update.success=User personal data has been successfully updated
// EN.news.toemail=I want to get news of website to email:
// EN.notification.toemail=I want to get notification to email:
// EN.organization.about=About organization (optional)
// EN.organization.categories=Tasks from which areas your organization is interested in
// EN.organization.documents=Organization registration documents
// EN.organization.edit=Edit organization data
// EN.organization.logo=Organization logo
// EN.organization.name=Organization full name
// EN.organization.position=Your position in the organization
// EN.organization.reg.link=Link (if available)
// EN.organization.registration.panel.header.docs=or attach documents on registration of the organization
// EN.organization.registration.panel.header.link=Provide a link to the registration of the organization in the registry
// EN.organization.registration.panel.header.main=Organization registration
// EN.organization.site.url=Link to the organization site (if available)
// EN.partner.registration.panel.header.main=Partner registration
// EN.password.confirm=Password again:
// EN.password.current=Current password:
// EN.password.name=Password
// EN.password.new=New password:
// EN.phone=Phone number
// EN.phonenumber.name=Phonenumber (optional)
// EN.profile.account.deletion=Account deletion
// EN.profile.account.settings=Account settings
// EN.profile.display=Display in profile
// EN.profile.notices=Notices
// EN.profile.organization.data=Organization data
// EN.profile.subscriptions=Subscriptions
// EN.profile.user.data=My data
// EN.profile.user.tasks=My tasks
// EN.profile.users.management=Users management
// EN.profile=User profile
// EN.provide.sum=Enter the amount
// EN.registration.confirmed=Your email confirmed!
// EN.registration.notconfirmed=Your email did not confirmed!
// EN.registration.panel.header.sec=Enter data:
// EN.registration.panel.header.user.main=User registration
// EN.registration.success=Congratulation! Your registration succeeded! Message was sent to your email. Please confirm it. 
// EN.registration.url=Organization registration link
// EN.selector.default.status=Nothing selected
// EN.settings.email=Email (not editable)
// EN.settings.news=I want to receive news to email
// EN.settings.notifications=I want to receive notices from my account to email
// EN.settings.password.confirm=Repeat new password
// EN.settings.password.current=Current password
// EN.settings.password.new=New password
// EN.sex.female.name=M
// EN.sex.male.name=F
// EN.sex.name=Sex
// EN.showinprofile=Show in profile:
// EN.site.url=Link to the organization site
// EN.skype.name=Skype:
// EN.skype=Skype
// EN.socialnetwork.name=Link to social networks:
// EN.stage.about=Description of work at this stage
// EN.stage.duration=Stage duration
// EN.stage.name=Stage name
// EN.stage=Stage
// EN.story.answer.join.team=Join our team!
// EN.story.modal.photo.upload=Upload new photo
// EN.story.organization.about=About organization
// EN.story.organization.site=Organization site
// EN.story.partner.about=About partner
// EN.story.partner.site=Partner site
// EN.story.progress.description=Progress
// EN.story.question.be.performer=Or do you want to help this or another NGO in their mission?
// EN.story.question.find.performers=Do you want to find performers for your task?
// EN.story.result.description=Results
// EN.story.task.description=Task description
// EN.story.volunteer.about=About volunteer
// EN.task.about.description=Tell us exactly what you need. Describe what source materials and data you have, tell us how you plan to interact with the task performer.
// EN.task.about=Describe your task
// EN.task.author=Task author
// EN.task.categories=Categories
// EN.task.category.description=We recommend choosing from one to three categories. If you don't know what category your task belongs to, we recommend that you study the existing tasks on the site in the help section.
// EN.task.category=What area is your task from
// EN.task.create.partner=Create partner task
// EN.task.create.volunteer=Create volunteer task
// EN.task.create=Create tasks
// EN.task.deadline=The task is relevant until
// EN.task.duration=Duration
// EN.task.edit.partner=Edit partner task
// EN.task.edit.volunteer.description=Changes will be reflected in the published task without administrator approval
// EN.task.edit.volunteer=Edit volunteer task
// EN.task.edit=Edit task
// EN.task.filter.date=date
// EN.task.filter.duration=duration
// EN.task.info.categories=Task in categories
// EN.task.info.deadline=Actual until
// EN.task.info.duration=Task duration
// EN.task.info.outcome=Work results
// EN.task.info.requirement.volunteer=Volunteer requirements
// EN.task.info.saved.amount=Help to save
// EN.task.info.stage.duration=Stage duration
// EN.task.info.stages=Task stages
// EN.task.interview.volunteer=Volunteer interview required
// EN.task.label.by.date=By date
// EN.task.label.by.duration=By duration
// EN.task.name.description=Come up with a name for the task.
// EN.task.name=Task name
// EN.task.outcome.description=Write exactly how you see the result of the work, in what format do you want to see the files, do you need advice or instructions on how to use these files, will you need further support for the task, etc.
// EN.task.outcome=What do you want to get in the end
// EN.task.partner.deadline.description=Provide the date by which you need to find a partner. In case you do not find a partner before this date, the task will automatically close.
// EN.task.register.partner=Create partner task
// EN.task.register.volunteer.description=You can edit the task later, before the administrator approves it
// EN.task.register.volunteer=Create volunteer task
// EN.task.requirement.volunteer.description=You can add up to two volunteer requirements. Please, indicate only really important requirements for the task (experience, portfolio, knowledge in a specific area). Indicate if you would like to conduct a short interview with the volunteer before starting work.
// EN.task.requirement.volunteer=What do you expect from a volunteer
// EN.task.reward.partner.description=Write down what benefits the partner will receive when completing the task. This can be a mention on a website, at an event, future collaboration, free advertising, etc.
// EN.task.reward.partner=Partner benefits
// EN.task.reward.volunteer.description=Indicate how you will reward the volunteer, this may be a recommendation letter, a mention on your website or event, a small cash reward etc.
// EN.task.reward.volunteer=Volunteer reward
// EN.task.reward=Reward
// EN.task.save=Save
// EN.task.saved.amount.description=Write the approximate amount (or the exact amount if you know it), which a volunteer can help you save. This will help volunteers evaluate their contributions and services.
// EN.task.saved.amount=Estimate how much money volunteer work can help you save
// EN.task.stages.add=Add stage
// EN.task.stages.partner.main.description=We have already added a basic work plan for your task, it consists of two stages from the approval of the plan with a partner to the delivery of the final work. You can edit existing stages, add new one. The plan should contain at least two, at max - seven stages. For each stage you should add a name and duration, also you can add a short description.
// EN.task.stages.partner.secondary.description=We will send you and task partners letters before stages deadlines and final task deadline.
// EN.task.stages.volunteer.main.description=We have already added a basic work plan for your task, it consists of two stages from the approval of the volunteer to the delivery of the final work. You can edit existing stages, add new one. The plan should contain at least two, at max - seven stages. For each stage you should add a name and duration, also you can add a short description.
// EN.task.stages.volunteer.secondary.description=We will send you and task performers letters before stages deadlines and final task deadline.
// EN.task.stages=Make a work plan
// EN.task.start.again=Start again
// EN.task.to=To task
// EN.task.volunteer.deadline.description=Provide the date by which you need to find a partner.In case you do not find a volunteer before this date, the task will automatically close.
// EN.tasks=Tasks
// EN.title.page.edit.data=Edit data
// EN.title.page.home=SKARB NGO
// EN.title.page.login=LogIn
// EN.title.page.profile=Profile
// EN.title.page.registration.organization=Organization registration
// EN.title.page.registration.partner=Partner registration
// EN.title.page.registration.volunteer=Volunteer registration
// EN.title.page.registration=Registration
// EN.title.page.story.edit=Edit success story
// EN.title.page.story.registration=Success story registration
// EN.title.page.story=Success story page
// EN.title.page.task.edit=Task edit
// EN.title.page.task.registration=New task registration
// EN.title.page.task.search=Task search
// EN.title.page.task=Task page
// EN.user.data.edit=Edit data
// EN.user.edit.panel.header=Edit data:
// EN.validationMessages.ContentType=File's content type should be on of {0}
// EN.validationMessages.CorporateEmail=Corporate email address is required
// EN.validationMessages.CurrentPassword=Invalid current password
// EN.validationMessages.Email=Email is incorrect
// EN.validationMessages.Future=Must be a future date
// EN.validationMessages.MaxFileSize=Max file size should be no greater than {1} megabyte(s)
// EN.validationMessages.NotBlank=Field cannot be blank
// EN.validationMessages.NotEmpty=Field can't be empty
// EN.validationMessages.NotEmptyFile=File should not be empty
// EN.validationMessages.NotNull=Field can't be empty
// EN.validationMessages.OrganizationName=Must not contain special characters
// EN.validationMessages.Password=Password is incorrect. Max length of password - {2}, min length of password {3}, must contain: upper case - at least {5}, lower case - at least {1}, spetial char - {4}
// EN.validationMessages.PasswordsMatch=Password and confirm password isn't equal
// EN.validationMessages.PersonName.firstName=First name must not contain special characters
// EN.validationMessages.PersonName.lastName=Last name must not contain special character
// EN.validationMessages.PhoneNumber=Phone number is incorrect
// EN.validationMessages.PositionName=Must not contain special characters
// EN.validationMessages.SiteUrl=Should be valid URL address
// EN.validationMessages.Size.categoryIds=Should be selected from {2} to {1} categories
// EN.validationMessages.Size.documents=No more than 3 files
// EN.validationMessages.Size.java.lang.String=Should be no more than {1} characters
// EN.validationMessages.typeMismatch.deadline=Must be in format 'DD.MM.YYYY'
// EN.validationMessages.UniqueEmail=Provided email address already taken
// EN.validationMessages.UniqueNgoName=Provided organization name already taken
// EN.validationMessages.UniquePartnerName=Provided partner name already taken
// EN.volunteer.registration.panel.header=Registration volunteer
// EN.volunteer.status.havetask=Have a task
// EN.volunteer.status.timeout=Time-out
// EN.volunteer.status.withouttask=Without task
// EN.volunteer.status=Volunteer status:
// EN.volunteer=Volunteer 










// RU.about.name=О себе
// RU.about.organization=Об оганизации
// RU.avatar.modal.title=Изменить аватарку пользоваетля
// RU.button.another.tasks=Другие задачи
// RU.button.as.organization=Как организация
// RU.button.as.partner=Как партнер
// RU.button.as.volunteer=Как волонтер
// RU.button.attach.document=Прикрепить документ
// RU.button.attach.file=Прикрепить файл
// RU.button.change.photo=Изменить фото
// RU.button.create.story=Создать историю успеха
// RU.button.delete=Удалить
// RU.button.login=Вход
// RU.button.organization=Неприбыльная организация
// RU.button.partner=Партнер
// RU.button.register=Зарегистрироваться
// RU.button.save.changes=Сохранить изменения
// RU.button.save=Сохранить изменения
// RU.button.upload.photo=Загрузить фото
// RU.button.upload=Загрузить
// RU.button.volunteer=Волонтер
// RU.categories.organization=Категории задач организации
// RU.category.name=Категория
// RU.choose.category=Выберите категорию
// RU.confirmpassword.name=Подтвердить пароль
// RU.day.month.year=ДД.ММ.ГГГГ
// RU.document.modal.title=Загрузить новый документ
// RU.document.upload.invalid=Неподдержывемый тип документа. Пожалуйста выберите другой файл
// RU.duration=Длительность
// RU.email.name=Email
// RU.first.name=Имя
// RU.header.change.lang=Изменить язык
// RU.header.lang.eng=Англ
// RU.header.lang.ru=Рус
// RU.header.lang.ua=Укр
// RU.invalidCredentials=Неверный логин или пароль!
// RU.label.about.project=О проекте
// RU.label.about.us=О нас
// RU.label.can.upload=Вы можете загрузить еще
// RU.label.cancel=Отменить
// RU.label.choose.all=Выбрать все
// RU.label.completed.tasks=Завершенные задачи
// RU.label.confirm.action=Подтвердите действие
// RU.label.confirm=Подтвердить
// RU.label.contact.us=Связаться с нами
// RU.label.contacts=Контакты
// RU.label.currency.RUB.name=рублей
// RU.label.currency.RUB=\u20BD
// RU.label.currency.UAH.name=гривен
// RU.label.currency.UAH=\u20B4
// RU.label.currency.USD.name=долларов
// RU.label.currency.USD=\u0024
// RU.label.date.date.completed=Дата завершения
// RU.label.draft.tasks=Черновики
// RU.label.duration.measure.DAY.name=дней
// RU.label.duration.measure.DAY=Дни
// RU.label.duration.measure.WEEK.name=недели
// RU.label.duration.measure.WEEK=Недели
// RU.label.enter=Войти
// RU.label.forgotPassword=Забыли пароль?
// RU.label.help=Помощь
// RU.label.inprogress.tasks=Задачи в работе
// RU.label.invite=Пригласить
// RU.label.login=Логин
// RU.label.main=Главная
// RU.label.members=Участники
// RU.label.news=Новости
// RU.label.no.completed.tasks=У вас пока нету завершенных задач
// RU.label.no.draft.tasks=У вас пока нету черновиков
// RU.label.no.inprogress.tasks=У вас пока нету задач в работе
// RU.label.no.published.tasks=У вас пока нету опубликованных задач
// RU.label.on.site.since=На сайте с
// RU.label.organizations=Организации
// RU.label.partners=Партнеры
// RU.label.password=Пароль
// RU.label.performers=Исполнители
// RU.label.photo=фото
// RU.label.potential.performers=Потенциальные исполнители
// RU.label.published.tasks=Опубликованные задачи
// RU.label.registration.as=Вы регистрируетесь как
// RU.label.registration=Регистрация
// RU.label.remove.from.task=Снять с задачи
// RU.label.respond=Откликнуться
// RU.label.responded=Откликнулись
// RU.label.rules=Правила
// RU.label.save.for.ngo=Экономия для НКО
// RU.label.search.results.tasks=задач(и)
// RU.label.search.results=Результаты поиска
// RU.label.search.tasks.partner=Для партнеров
// RU.label.search.tasks.volunteer=Для волонтеров
// RU.label.show.more=Показать больше
// RU.label.sort.by=Сортировка по
// RU.label.task.categories=Категории
// RU.label.task.duration.LONG_TERM=Длительная
// RU.label.task.duration.UP_TO_MONTH=До месяца
// RU.label.task.duration.UP_TO_TWO_WEEKS=До двух недель
// RU.label.task.duration.UP_TO_WEEK=До недели
// RU.label.task.duration=Длительность задачи
// RU.label.task.status.ALL=Все задачи
// RU.label.task.status.COMPLETED=Завершенная
// RU.label.task.status.IN_PROGRESS=В работе
// RU.label.task.status.NEW=Новая
// RU.label.task.status.PUBLISHED=Опубликовано
// RU.label.task.status.URGENT=Срочная
// RU.label.task.status=Статус задачи
// RU.label.tasks.completed=Завершенные
// RU.label.tasks.draft=Черновики
// RU.label.tasks.in_progress=В работе
// RU.label.tasks.published=Опубликованные
// RU.label.tasks.search=Поиск задач
// RU.label.tasks=Задачи
// RU.label.title.organization.representatives=Представители организаций
// RU.label.title.volunteers=Волонтеры
// RU.label.volunteers=Волонтеры
// RU.label.works.in.categories=Работает в категориях
// RU.last.name=Фамилия
// RU.link.register=Нет личного кабинета? Зарегистрируйтесь
// RU.linkedin.name=Ссылка на LinkedIn:
// RU.linkedin.url=Ссылка на LinkedIn
// RU.logo.modal.title=Загрузить новый логотип
// RU.logo.upload.invalid=Неподдержывемый тип логотипа. Пожалуйста выберите другой файл
// RU.logoutSuccess=Вы успешно вышли с аккаунта.
// RU.messages.account.settings.update.success=Настройки аккаунта были успешно обновлены
// RU.messages.avatar.upload.failure=Ошибка при загрузке аватарки. Пожалуйста повторите попытку позднее
// RU.messages.avatar.upload.success=Новая аватарка была успешно загружена
// RU.messages.error.something.went.wrong=Ой! Что-то пошло не так!
// RU.messages.error.try.again=Попробуйте повторить запрос или напишите нам о проблеме.
// RU.messages.organization.data.update.success=Данные организации были успешно обновлены
// RU.messages.organization.document.delete.failure=Ошибка при удалении документа. Пожалуйста, повторите попытку позже
// RU.messages.organization.document.delete.success=Документ был успешно удален
// RU.messages.organization.document.update.success=Новый документ был успешно загружен
// RU.messages.organization.logo.delete.failure=Ошибка при удалении логотипа. Пожалуйста, повторите попытку позже
// RU.messages.organization.logo.delete.success=Логотип был успешно удален
// RU.messages.organization.logo.update.success=Новый логотип был успешно загружен
// RU.messages.story.edit.success=История успеха была успешно отредактирована. Ожидайте одобрения администратором
// RU.messages.story.photo.delete.failure=Ошибка при удалении фото. Пожалуйста, повторите попытку позже
// RU.messages.story.photo.delete.success=Фото было успешно удалено
// RU.messages.story.photo.upload.fail=Неверный размер или тип фото. Пожалуйста выберите другое.
// RU.messages.story.photo.upload.success=Новое фото было успешно загружено
// RU.messages.story.registration.success=Новая история успеха была успешно зарегистрирована. Ожидайте одобрения администратором
// RU.messages.task.edit.not.allowed=Вы не можете редактировать уже опубликованную задачу!
// RU.messages.task.edit.success=Задача была успешно отредактирована.
// RU.messages.task.registration.success=Новая задача была успешно зарегистрирована. Ожидайте одобрения администратором
// RU.messages.task.respond.confirm.failure=Что-то пошло не так. Возможно, данный исполнитель уже подтвержден?
// RU.messages.task.respond.confirm.success=Вы успешно подтвердили нового исполнителя для данной задачи.
// RU.messages.task.respond.confirm=Вы действительно хотите откликнуться на данную задачу?
// RU.messages.task.respond.confirmation.confirm=Вы действительно хотите подтвердить данного откликнувшегося пользователя?
// RU.messages.task.respond.failure=Что-то пошло не так. Возможно, вы уже откликались на данную задачу?
// RU.messages.task.respond.success=Вы успешно откликнулись на данную задачу. Ожидайте ответа от автора.
// RU.messages.tasks.stages.add.fail=Вы не можете добавить больше этапов для задачи
// RU.messages.user.data.update.success=Личные данные пользователя были успешно обновлены
// RU.news.toemail=Я хочу получать новости на email:
// RU.notification.toemail=Я хочу получать уведомления на email:
// RU.organization.about=Расскажите об организации (не обязательно для заполнения)
// RU.organization.categories=Задачи из каких областей интересны вашей организации
// RU.organization.documents=Документы о регистрации организации
// RU.organization.edit=Редактировать данные организации
// RU.organization.logo=Логотип организации
// RU.organization.name=Полное название организации
// RU.organization.position=Ваша должность в организации
// RU.organization.reg.link=Ссылка (при наличии)
// RU.organization.registration.panel.header.docs=или прикрепите документы о регистрации организации
// RU.organization.registration.panel.header.link=Укажите ссылку на регистрацию организации в реестре
// RU.organization.registration.panel.header.main=Регистрация организации
// RU.organization.site.url=Ссылка на сайт организации (если есть)
// RU.partner.registration.panel.header.main=Регистрация партнера
// RU.password.confirm=Пароль еще раз:
// RU.password.current=Текущий пароль:
// RU.password.name=Пароль
// RU.password.new=Новый пароль:
// RU.phone=Номер телефона
// RU.phonenumber.name=Телефонный номер (не обязательно для заполнения)
// RU.profile.account.deletion=Удаление аккаунта
// RU.profile.account.settings=Настройки аккаунта
// RU.profile.display=Отображать в профиле
// RU.profile.notices=Уведомления
// RU.profile.organization.data=Данные организации
// RU.profile.subscriptions=Подписки
// RU.profile.user.data=Мои данные
// RU.profile.user.tasks=Мои задачи
// RU.profile.users.management=Управление пользователями
// RU.profile=Личный кабинет
// RU.provide.sum=Укажите сумму
// RU.registration.confirmed=Ваш email подтверждено!
// RU.registration.notconfirmed=Ваш email не подтверждено!
// RU.registration.panel.header.sec=Введите данные:
// RU.registration.panel.header.user.main=Регистрация пользователя
// RU.registration.success=Поздравляем! Ваша регистрация прошла успешно! На Ваш Email було отправлено сообщение. Подтвердите указаный электронный ящик. 
// RU.registration.url=Ссылка на регистрацию организации
// RU.selector.default.status=Ничего не выбрано
// RU.settings.email=Email (не редактируется)
// RU.settings.news=Я хочу получать новости на email
// RU.settings.notifications=Я хочу получать уведомления с аккаунте на email
// RU.settings.password.confirm=Новый пароль еще раз
// RU.settings.password.current=Текущий пароль
// RU.settings.password.new=Новый пароль
// RU.sex.female.name=Ж
// RU.sex.male.name=М
// RU.sex.name=Пол
// RU.showinprofile=Отображается в профиле:
// RU.site.url=Ссылка на сайт организации
// RU.skype.name=Skype:
// RU.skype=Skype
// RU.socialnetwork.name=Ссылка на социальные сети:
// RU.stage.about=Описание работы на данном этапе
// RU.stage.duration=Длительность этапа работы
// RU.stage.name=Название этапа работы
// RU.stage=Этап
// RU.story.answer.join.team=Вступайте в нашу команду!
// RU.story.modal.photo.upload=Загрузить новое фото
// RU.story.organization.about=Об организации
// RU.story.organization.site=Сайт организации
// RU.story.partner.about=О партнере
// RU.story.partner.site=Сайт партнера
// RU.story.progress.description=Ход работы
// RU.story.question.be.performer=Или хотите помочь этой или другой НКО в их миссии?
// RU.story.question.find.performers=Хотите найти исполнителей для своей задачи?
// RU.story.result.description=Итоги работы
// RU.story.task.description=Описание задачи
// RU.story.volunteer.about=О волонтере
// RU.task.about.description=Расскажите, что именно вам нужно. Опишите, какие у вас есть исходные материалы и данные, расскажите, как вы планируете взаимодействовать с исполнителем задачи.
// RU.task.about=Опишите ваше задачу
// RU.task.author=Автор задачи
// RU.task.categories=Категории
// RU.task.category.description=Мы рекомендуем выбрать от одной до трех категорий. Если вы не знаете, к какой категории относиться ваша задача, рекомендуем вам изучить существующие задачи на сайте в разделе помощь.
// RU.task.category=Из какой области ваша задача
// RU.task.create.partner=Создать задачу для партнера
// RU.task.create.volunteer=Создать задачу для волонтера
// RU.task.create=Создать задачу
// RU.task.deadline=Задача актуальна до
// RU.task.duration=Длительность
// RU.task.edit.partner=Редактирование задачи для партнера
// RU.task.edit.volunteer.description=Изменения отобразятся в опубликованной задаче без одобрения администратора
// RU.task.edit.volunteer=Редактирование задачи для волонтера
// RU.task.edit=Редактировать
// RU.task.filter.date=дате
// RU.task.filter.duration=длительности
// RU.task.info.categories=Задача в категориях
// RU.task.info.deadline=Актуально до
// RU.task.info.duration=Длительность задачи
// RU.task.info.outcome=Итоги работы
// RU.task.info.requirement.volunteer=Требования к волонтеру
// RU.task.info.saved.amount=Поможет сэкономить
// RU.task.info.stage.duration=Длительность этапа
// RU.task.info.stages=Этапы работы над задачей
// RU.task.interview.volunteer=Требуется собеседование с волонтером
// RU.task.label.by.date=По дате
// RU.task.label.by.duration=По длительности
// RU.task.name.description=Придумайте название задачи.
// RU.task.name=Название задачи
// RU.task.outcome.description=Напишите, каким именно вы видите итог работы, в каком именно формате вы хотите видеть файлы, нужна ли вам консультация или инструкция, как этими файлами пользоваться, будете ли вы нуждаться в дальнейшей поддержке по задаче и т.д.
// RU.task.outcome=Что вы хотите получить в итоге
// RU.task.partner.deadline.description=Укажите дату, до которой вам нужно найти партнера. В случае, если вы не найдете партнера до этой даты, задача автоматически закроется.
// RU.task.register.partner=Создание задачи для партнера
// RU.task.register.volunteer.description=Вы сможете отредактировать задачу позже, до одобрения администратором
// RU.task.register.volunteer=Создание задачи для волонтера
// RU.task.requirement.volunteer.description=Вы можете добавить до двух требований к волонтеру. Пожалуйста, указывайте только действительно важные требования для задачи (наличие опыта, портфолио, знания в конкретной области). Укажите, хотите ли вы провести с волонтером небольшое собеседование перед началом работы.
// RU.task.requirement.volunteer=Чего вы ждете от волонтера
// RU.task.reward.partner.description=Напишите, какие преимущества при выполнении задачи получит партнер. Это может быть упоминание на сайте, на мероприятии, сотрудничество в будущем, бесплатная реклама и т.д.
// RU.task.reward.partner=Преимущества для партнера
// RU.task.reward.volunteer.description=Укажите, как вы вознаградите волонтера, это может быть рекомендательное благодарственное письмо, упоминание на вашем сайте или мероприятии, небольшое денежное вознаграждение и т.д.
// RU.task.reward.volunteer=Вознаграждение волонтеру
// RU.task.reward=Вознаграждение
// RU.task.save=Сохранить
// RU.task.saved.amount.description=Напишите примерную сумму (либо точную если она вам известна), которую вам поможет сэкономить волонтер. Это поможет волонтерам оценить свой вклад и услуги.
// RU.task.saved.amount=Оцените, сколько вам поможет сэкономить работа волонтера
// RU.task.stages.add=Добавить этап
// RU.task.stages.partner.main.description=Мы уже добавили базовый план работы для вашей задачи, он состоит из двух этапов от утверждения плана с партнером до сдачи финальной работы. Вы можете отредактировать существующие этапы, добавить дополнительные. В плане должно быть минимум два, максимум - семь этапов. Для каждого этапа необходимо добавить название и длительность, также можно добавить краткое описание.
// RU.task.stages.partner.secondary.description=Мы будем отправлять вам и партнерам задачи письма перед дедлайнами этапов и финальным дедлайном задачи.
// RU.task.stages.volunteer.main.description=Мы уже добавили базовый план работы для вашей задачи, он состоит из двух этапов от утверждения волонтера до сдачи финальной работы. Вы можете отредактировать существующие этапы, добавить дополнительные. В плане должно быть минимум два, максимум - семь этапов. Для каждого этапа необходимо добавить название и длительность, также можно добавить кототкое описание.
// RU.task.stages.volunteer.secondary.description=Мы будем отправлять вам и исполнителям задач письма перед дедлайнами этапов и финальным дедлайном задачи.
// RU.task.stages=Составьте план работы
// RU.task.start.again=Начать заново
// RU.task.to=К задаче
// RU.task.volunteer.deadline.description=Укажите дату, до которой вам нужно найти волонтера. В случае, если вы не найдете волонтера до этой даты, задача автоматически закроется.
// RU.tasks=Задачи
// RU.title.page.edit.data=Редактирование данных
// RU.title.page.home=SKARB NGO
// RU.title.page.login=Вход
// RU.title.page.profile=Личный кабинет
// RU.title.page.registration.organization=Регистрация организации
// RU.title.page.registration.partner=Регистрация партнера
// RU.title.page.registration.volunteer=Регистрация волонтера
// RU.title.page.registration=Регистрация
// RU.title.page.story.edit=Редактирование истории успеха
// RU.title.page.story.registration=Создание истории успеха
// RU.title.page.story=Страница истории успеха
// RU.title.page.task.edit=Редактирование задачи
// RU.title.page.task.registration=Регистрация новой задачи
// RU.title.page.task.search=Поиск задач
// RU.title.page.task=Страница задачи
// RU.user.data.edit=Редактировать данные
// RU.user.edit.panel.header=Редактировать данные:
// RU.validationMessages.ContentType=Должен быть в формате {0}
// RU.validationMessages.CorporateEmail=Адрес должен бить корпоративным
// RU.validationMessages.CurrentPassword=Неверный текущий пароль
// RU.validationMessages.Email=Email введено не коректно
// RU.validationMessages.Future=Дата должна быть в будущем
// RU.validationMessages.MaxFileSize=Максимальный размер файла логотипа должен бить не больше {1} мегабайт
// RU.validationMessages.NotBlank=Поле не может быть пустым
// RU.validationMessages.NotEmpty=Поле не может быть пустым
// RU.validationMessages.NotEmptyFile=Файл не должен быть пустым
// RU.validationMessages.NotNull=Поле не может быть пустым
// RU.validationMessages.OrganizationName=Не должно содержать символов
// RU.validationMessages.Password=Пароль введено не коректно. Максимальная длина пароля {2}, минимальная длина пароля {3}, должен содержать: больших букв - не меньше {5}, малых букв - не меньше {1}, специальных символов - {4}
// RU.validationMessages.PasswordsMatch=Пароль и подтверждение не совпадают
// RU.validationMessages.PersonName.firstName=Имя не может содержать символы и знаки
// RU.validationMessages.PersonName.lastName=Фамилия не может содержать символы и знаки
// RU.validationMessages.PhoneNumber=Номер телефона введено не коректно
// RU.validationMessages.PositionName=Не должно содержать символов
// RU.validationMessages.SiteUrl=Должен быть вылидный URL адрес
// RU.validationMessages.Size.categoryIds=Должно быть выбрано от {2} до {1} категорий
// RU.validationMessages.Size.documents=Не больше трех файлов
// RU.validationMessages.Size.java.lang.String=Должно быть не больше {1} символов
// RU.validationMessages.typeMismatch.deadline=Должно быть в формате 'ДД.ММ.ГГГГ'
// RU.validationMessages.UniqueEmail=Указанный email адрес уже занят
// RU.validationMessages.UniqueNgoName=Организация с указанным именем уже зарегестрирована
// RU.validationMessages.UniquePartnerName=Партнер с указанным именем уже зарегестрирован
// RU.volunteer.registration.panel.header=Регистрация волонтера
// RU.volunteer.status.havetask=Работаю над задачей
// RU.volunteer.status.timeout=Тайм-аут
// RU.volunteer.status.withouttask=Без задач
// RU.volunteer.status=Статус волонтера на сайте:
// RU.volunteer=Волонтер





// UA.about.name=Про себе
// UA.about.organization=Про організацію
// UA.avatar.modal.title=Змінити аватарку користувача
// UA.button.another.tasks=Інші завдання
// UA.button.as.organization=Як організація
// UA.button.as.partner=Як партнер
// UA.button.as.volunteer=Як волонтер
// UA.button.attach.document=Додати документ
// UA.button.attach.file=Додати файл
// UA.button.change.photo=Змінити фото
// UA.button.create.story=Створити історію успіху
// UA.button.delete=Видалити
// UA.button.login=Увійти
// UA.button.organization=Неприбуткова організація
// UA.button.partner=Партнер
// UA.button.register=Зареєструватися
// UA.button.save.changes=Зберегти зміни
// UA.button.save=Зберігти зміни
// UA.button.upload.photo=Завантажити фото
// UA.button.upload=Завантажити
// UA.button.volunteer=Волонтер
// UA.categories.organization=Категорії завдань організації
// UA.category.name=Категорія
// UA.choose.category=Оберіть категорію
// UA.confirmpassword.name=Підтвердити пароль
// UA.day.month.year=ДД.ММ.РРРР
// UA.document.modal.title=Завантажити новий документ
// UA.document.upload.invalid=Непідтримуваний тип документу. Будь ласка оберіть інший файл
// UA.duration=Тривалість
// UA.email.name=Email
// UA.first.name=Ім'я
// UA.header.change.lang=Змінити мову
// UA.header.lang.eng=Англ
// UA.header.lang.ru=Рос
// UA.header.lang.ua=Укр
// UA.invalidCredentials=Невірний логін чи пароль!
// UA.label.about.project=Про проект
// UA.label.about.us=Про нас
// UA.label.can.upload=Ви можете завантажити ще
// UA.label.cancel=Відмінити
// UA.label.choose.all=Обрати все
// UA.label.completed.tasks=Закінчені завдання
// UA.label.confirm.action=Підтвердіть дію
// UA.label.confirm=Підтвердити
// UA.label.contact.us=Зв'язатися с нами
// UA.label.contacts=Контакти
// UA.label.currency.RUB.name=рублів
// UA.label.currency.RUB=\u20BD
// UA.label.currency.UAH.name=гривень
// UA.label.currency.UAH=\u20B4
// UA.label.currency.USD.name=долларів
// UA.label.currency.USD=\u0024
// UA.label.date.date.completed=Дата закінчення
// UA.label.draft.tasks=Чернетки
// UA.label.duration.measure.DAY.name=днів
// UA.label.duration.measure.DAY=Дні
// UA.label.duration.measure.WEEK.name=тижнів
// UA.label.duration.measure.WEEK=Тижні
// UA.label.enter=Увійти
// UA.label.forgotPassword=Забули пароль?
// UA.label.help=Допомога
// UA.label.inprogress.tasks=Завдання в роботі
// UA.label.invite=Запросити
// UA.label.login=Логін
// UA.label.main=Головна
// UA.label.members=Учасники
// UA.label.news=Новини
// UA.label.no.completed.tasks=У вас поки що немає закінчених завдань
// UA.label.no.draft.tasks=У вас поки немає чернеток
// UA.label.no.inprogress.tasks=У вас поки що немає завдань в роботі
// UA.label.no.published.tasks=У вас поки що немає опублікованих завдань
// UA.label.on.site.since=На сайті з
// UA.label.organizations=Організації
// UA.label.partners=Партнери
// UA.label.password=Пароль
// UA.label.performers=Виконавці
// UA.label.photo=фото
// UA.label.potential.performers=Потенційні виконавці
// UA.label.published.tasks=Опубліковані завдання
// UA.label.registration.as=Ви реєструєтеся як
// UA.label.registration=Реєстрація
// UA.label.remove.from.task=Зняти з завдання
// UA.label.respond=Відгукнутися
// UA.label.responded=Відгукнулися
// UA.label.rules=Правила
// UA.label.save.for.ngo=Економія для НКО
// UA.label.search.results.tasks=завдань
// UA.label.search.results=Результати пошуку
// UA.label.search.tasks.partner=Для партнерів
// UA.label.search.tasks.volunteer=Для волонтерів
// UA.label.show.more=Показати більше
// UA.label.sort.by=Сортування по
// UA.label.task.categories=Категорії
// UA.label.task.duration.LONG_TERM=Довготривала
// UA.label.task.duration.UP_TO_MONTH=До місяця
// UA.label.task.duration.UP_TO_TWO_WEEKS=До двох тижнів
// UA.label.task.duration.UP_TO_WEEK=До тижня
// UA.label.task.duration=Тривалість завдання
// UA.label.task.status.ALL=Всі завдання
// UA.label.task.status.COMPLETED=Закінчене
// UA.label.task.status.IN_PROGRESS=В роботі
// UA.label.task.status.NEW=Нове
// UA.label.task.status.PUBLISHED=Опубліковане
// UA.label.task.status.URGENT=Термінове
// UA.label.task.status=Статус завдання
// UA.label.tasks.completed=Закінчені
// UA.label.tasks.draft=Чернетки
// UA.label.tasks.in_progress=В роботі
// UA.label.tasks.published=Опубліковані
// UA.label.tasks.search=Пошук завдань
// UA.label.tasks=Завдання
// UA.label.title.organization.representatives=Представники організацій
// UA.label.title.volunteers=Волонтери
// UA.label.volunteers=Волонтери
// UA.label.works.in.categories=Працює в категоріях
// UA.last.name=Прізвище
// UA.link.register=Не маєш особистого кабінету? Зареєстуйся
// UA.linkedin.name=Посилання на LinkedIn:
// UA.linkedin.url=Посилання на LinkedIn
// UA.logo.modal.title=Завантажити новій логотип
// UA.logo.upload.invalid=Непідтримуваний тип логотипу. Будь ласка оберіть інший файл
// UA.logoutSuccess=Ви успішно вийшли з аккаунту.
// UA.messages.account.settings.update.success=Налаштування аккаунту були успішно оновлені
// UA.messages.avatar.upload.failure=Помилка при завантаженні аватарки. Будь ласка спробуйте пізніше
// UA.messages.avatar.upload.success=Нова аватарка була успішно завантажена
// UA.messages.error.something.went.wrong=Упс! Щось пішло не так!
// UA.messages.error.try.again=Спробуйте повторити запит, або напишіть нам про проблему.
// UA.messages.organization.data.update.success=Дані організації були успішно оновлені
// UA.messages.organization.document.delete.failure=Помилка при видаленні документу. Будь ласка спробуйте пізніше
// UA.messages.organization.document.delete.success=Документ був успішно відалений
// UA.messages.organization.document.update.success=Новий документ був успішно завантажений
// UA.messages.organization.logo.delete.failure=Помилка при видаленні логотипу. Будь ласка спробуйте пізніше
// UA.messages.organization.logo.delete.success=Логотип був успішно виделений
// UA.messages.organization.logo.update.success=Новий логотип був успішно завантажений
// UA.messages.story.edit.success=Історія успеху була успішно відредагована. Чекайте схвалення адміністратором
// UA.messages.story.photo.delete.failure=Помилка при видаленні фото. Будь ласка спробуйте пізніше
// UA.messages.story.photo.delete.success=Фото було успішно видалено
// UA.messages.story.photo.upload.fail=Невірній розмір або тип фото. Будь ласка оберіть інше.
// UA.messages.story.photo.upload.success=Нове фото було успішно завантажено
// UA.messages.story.registration.success=Нова історія успеху була успішно зареєстрована. Чекайте схвалення адміністратором
// UA.messages.task.edit.not.allowed=Вы не можете редагувати вже опубліковане завдання!
// UA.messages.task.edit.success=Завдання було успішно відредаговано.
// UA.messages.task.registration.success=Нова завдання було успішно зареєстрована. Чекайте схвалення адміністратором
// UA.messages.task.respond.confirm.failure=Щось пішло не так. Можливо цей виконавець вже підтверджений?
// UA.messages.task.respond.confirm.success=Ви успішно підтвердили нового виконавця на це завдання.
// UA.messages.task.respond.confirm=Ви дійсно хочете відгукнутися на це завдання?
// UA.messages.task.respond.confirmation.confirm=Ви дійсно хочете підтвердити цього відгукнувшугося користувача?
// UA.messages.task.respond.failure=Щось пішло не так. Можливо, ви вже відгукувалися на це завдання?
// UA.messages.task.respond.success=Ви успішно відгукнулися на це завдання. Чекайте відповіді від автора.
// UA.messages.tasks.stages.add.fail=Ви не можете додати більше етапів для завдання
// UA.messages.user.data.update.success=Особисті дані користувача були успішно оновлені
// UA.news.toemail=Я хочу отримувати новини cайту на email:
// UA.notification.toemail=Я хочу отримувати повідомлення на email:
// UA.organization.about=Розкажіть про організацію (не обов'язково для заповнення)
// UA.organization.categories=Завдання з яких областей цікаві вашій організації
// UA.organization.documents=Реєстраційні документи організації
// UA.organization.edit=Редагувати дані організації
// UA.organization.logo=Логотип організації
// UA.organization.name=Повна назва організації
// UA.organization.position=Ваша посада в організації
// UA.organization.reg.link=Посилання (при наявності)
// UA.organization.registration.panel.header.docs=або прикріпіть документи про реєстрацію організації
// UA.organization.registration.panel.header.link=Вкажіть посилання на реєстрацію організації в реєстрі
// UA.organization.registration.panel.header.main=Реєстрація організації
// UA.organization.site.url=Посилання на сайт організації (якщо є)
// UA.partner.registration.panel.header.main=Реєстрація партнера
// UA.password.confirm=Пароль ще раз:
// UA.password.current=Поточний пароль:
// UA.password.name=Пароль
// UA.password.new=Новий пароль:
// UA.phone=Телефонний номер
// UA.phonenumber.name=Телефоний номер (не обов'язково для заповнення)
// UA.profile.account.deletion=Видалення аккаунту
// UA.profile.account.settings=Налаштування аккаунту
// UA.profile.display=Відображати в профілі
// UA.profile.notices=Повідомлення
// UA.profile.organization.data=Дані організації
// UA.profile.subscriptions=Підписки
// UA.profile.user.data=Мої дані
// UA.profile.user.tasks=Мої задачі
// UA.profile.users.management=Управління користувачами
// UA.profile=Особистий кабінет
// UA.provide.sum=Вкажіть суму
// UA.registration.confirmed=Ваш email підтверджено!
// UA.registration.notconfirmed=Ваш email не підтверджено!
// UA.registration.panel.header.sec=Введіть данні:
// UA.registration.panel.header.user.main=Реєстрація користувача
// UA.registration.success=Вітаємо! Ваша реєстрація успішна! На Ваш Email було відправлено повідомлення. Підтвердьте зазначену електронну скриньку. 
// UA.registration.url=Посилання на реєстрацію організації
// UA.selector.default.status=Нічого не обрано
// UA.settings.email=Email (не редагується)
// UA.settings.news=Я хочу отримувати новини на email
// UA.settings.notifications=Я хочу отримувати повідомлення з аккаунту на email
// UA.settings.password.confirm=Повторити новий пароль
// UA.settings.password.current=Поточний пароль
// UA.settings.password.new=Новий пароль
// UA.sex.female.name=Ж
// UA.sex.male.name=Ч
// UA.sex.name=Стать
// UA.showinprofile=Відображається в профілі
// UA.site.url=Посилання на сайт організації
// UA.skype.name=Skype:
// UA.skype=Skype
// UA.socialnetwork.name=Посилання на соціальні мережі:
// UA.stage.about=Опис роботи на даному етапі
// UA.stage.duration=Тривалість етапу роботи
// UA.stage.name=Назва етапу роботи
// UA.stage=Етап
// UA.story.answer.join.team=Приєднуйтесь до нашої команди!
// UA.story.modal.photo.upload=Завантажити нові фото
// UA.story.organization.about=Про організацію
// UA.story.organization.site=Сайт організації
// UA.story.partner.about=Про партнера
// UA.story.partner.site=Сайт партнера
// UA.story.progress.description=Хід работи
// UA.story.question.be.performer=Або хочете допомогти цій або іншій НКО в їх місії?
// UA.story.question.find.performers=Хочете знайти виконавців для свого заадання?
// UA.story.result.description=Результати работи
// UA.story.task.description=Опис завдання
// UA.story.volunteer.about=Про волонтера
// UA.task.about.description=Рохкажіть, що конкретно вам необхідно. Опишіть, які у вас є вихідні матеріали і дані, розкажіть, як ви плануєте взаємодіяти з виконавцями завдання.
// UA.task.about=Опишіть ваше завдання
// UA.task.author=Автор завдання
// UA.task.categories=Категорії
// UA.task.category.description=Ми рекомендуємо обрати від однієї до трьох категорій. Якщо ви не знаєте, до якої категорії відноситься ваше завдання, рекомендуємо вам ознайомитися з існуючими завданнями на сайті в розділі допомоги.
// UA.task.category=З якої сфери ваше завдання
// UA.task.create.partner=Створити завдання для партнера
// UA.task.create.volunteer=Створити завдання для волонтера
// UA.task.create=Створити завдання
// UA.task.deadline=Завдання актуальне до
// UA.task.duration=Тривалість
// UA.task.edit.partner=Редагування завдання для партнера
// UA.task.edit.volunteer.description=Зміни відобразяться в опублікованому завданні без згоди адміністратора
// UA.task.edit.volunteer=Редагування завдання для волонтера
// UA.task.edit=Редагувати
// UA.task.filter.date=даті
// UA.task.filter.duration=тривалості
// UA.task.info.categories=Завдання в категоріях
// UA.task.info.deadline=Актуально до
// UA.task.info.duration=Тривалість завдання
// UA.task.info.outcome=Підсумки роботи
// UA.task.info.requirement.volunteer=Вимоги до волонтера
// UA.task.info.saved.amount=Допоможе заощадити
// UA.task.info.stage.duration=Тривалість етапу
// UA.task.info.stages=Етапи роботи над завданням
// UA.task.interview.volunteer=Необхідна співбесіда з волонтером
// UA.task.label.by.date=По даті
// UA.task.label.by.duration=По тривалості
// UA.task.name.description=Придумайте назву завданню.
// UA.task.name=Назва завдання
// UA.task.outcome.description=Напишіть, яким саме ви бачите підсумок роботи, в якому саме форматі ви хочете бачити файли, чи потрібна вам консультація або інструкція, як цими файлами користуватися, чи будете ви потребувати подальшої підтримки по завданню і т.д.
// UA.task.outcome=Що ви хочете отримати в результаті
// UA.task.partner.deadline.description=Вкажіть дату, до якої вам необхідно знайти партнера. У випадку, якщо ви не знайдете партнера до цієї дати, завдання автоматично закриється.
// UA.task.register.partner=Створення завдання для партнера
// UA.task.register.volunteer.description=Ви зможите вдредагувати завдання пізніше, до схвалення адміністратором
// UA.task.register.volunteer=Створення завдання для волонтера
// UA.task.requirement.volunteer.description=Ви можете додати до двох вимог до волонтера. Будь ласка, вказуйте тільки дійсно важливі вимоги для завдання (наявність досвіду, портфоліо, знання в конкретній області). Вкажіть, чи хочете ви провести з волонтером невелику співбесіду перед початком роботи.
// UA.task.requirement.volunteer=Чого ви чекаєте від волонтера
// UA.task.reward.partner.description=Напишіть, які переваги при виконанні завдання отримає партнер. Це може бути згадка на сайті, на заході, співпраця в майбутньому, безкоштовна реклама і т.д.
// UA.task.reward.partner=Переваги для партнера
// UA.task.reward.volunteer.description=Вкажіть, як ви винагородити волонтера, це може бути рекомендаційний лист подяки, згадка на вашому сайті або заході, невелика грошова винагорода і т.д.
// UA.task.reward.volunteer=Винагорода волонтеру
// UA.task.reward=Винагорода
// UA.task.save=Зберегти
// UA.task.saved.amount.description=Напишіть приблизну суму (або точну якщо вона вам відома), яку вам допоможе заощадити волонтер. Це допоможе волонтерам оцінити свій внесок і послуги.
// UA.task.saved.amount=Оцініть, скільки вам допоможе заощадити робота волонтера
// UA.task.stages.add=Додати етап
// UA.task.stages.partner.main.description=Ми вже додали базовий план роботи для вашого завдання, він складається з двох етапів від затвердження плану з партнером до здачі фінальної роботи. Ви можете відредагувати існуючі етапи, додати додаткові. У плані має бути мінімум два, максимум - сім етапів. Для кожного етапу необхідно додати назву і тривалість, також можна додати короткий опис.
// UA.task.stages.partner.secondary.description=Ми будемо відправляти вам і партнерам завдання листи перед дедлайнами етапів і фінальним дедлайном завдання.
// UA.task.stages.volunteer.main.description=Ми вже додали базовий план роботи для вашого завдання, він складається з двох етапів від затвердження волонтеру до здачі фінальної роботи. Ви можете відредагувати існуючі етапи, додати додаткові. У плані має бути мінімум два, максимум - сім етапів. Для кожного етапу необхідно додати назву і тривалість, також можна додати короткий опис.
// UA.task.stages.volunteer.secondary.description=Ми будемо відправляти вам і виконавцям завдань листи перед дедлайнами етапів і фінальним дедлайном завдання.
// UA.task.stages=Складіть план роботи
// UA.task.start.again=Почати спочатку
// UA.task.to=До завдання
// UA.task.volunteer.deadline.description=Вкажіть дату, до якої вам необхідно знайти волонтера. У випадку, якщо ви не знайдете волонтера до цієї дати, завдання автоматично закриється.
// UA.tasks=Завдання
// UA.title.page.edit.data=Редагування даних
// UA.title.page.home=SKARB NGO
// UA.title.page.login=Вхід
// UA.title.page.profile=Особистий кабінет
// UA.title.page.registration.organization=Реєстрація організацї
// UA.title.page.registration.partner=Реєстрація партнера
// UA.title.page.registration.volunteer=Реєстрація волонтера
// UA.title.page.registration=Реєстрація
// UA.title.page.story.edit=Редагування історії успіху
// UA.title.page.story.registration=Створення історії успіху
// UA.title.page.story=Сторінка історії успіху
// UA.title.page.task.edit=Редагування завдання
// UA.title.page.task.registration=Реєстрація нового завдання
// UA.title.page.task.search=Пошук завдань
// UA.title.page.task=Сторінка завдання
// UA.user.data.edit=Редагувати дані
// UA.user.edit.panel.header=Редагувати дані:
// UA.validationMessages.ContentType=Повинен бути в форматі PDF, JPG, или PNG
// UA.validationMessages.CorporateEmail=Адреса повинна бути корпоративною
// UA.validationMessages.CurrentPassword=Невірний поточний пароль
// UA.validationMessages.Email=Email введено не коректно
// UA.validationMessages.Future=Дата повинна бути в майбутньому
// UA.validationMessages.MaxFileSize=Максимальний розмір файлу не повинен перевищувати {1} мегабайт
// UA.validationMessages.NotBlank=Поле не може бути пустим
// UA.validationMessages.NotEmpty=Поле не може бути порожнім
// UA.validationMessages.NotEmptyFile=Файл не повинен бути пустим
// UA.validationMessages.NotNull=Поле не може бути порожнім
// UA.validationMessages.OrganizationName=Не должно содержать символов
// UA.validationMessages.Password=Пароль введено не коректно. Максимальна довжина паролю {2}, мінімальна довжина паролю {3}, має містити: великих літер - щонайменше {5}, малих літер - щонайменше {1}, спеціальних символів - {4}
// UA.validationMessages.PasswordsMatch=Пароль та підтвердження не співпадають
// UA.validationMessages.PersonName.firstName=Ім'я не може містити символи та розділові знаки
// UA.validationMessages.PersonName.lastName=Призвище не може містити символи та розділові знаки
// UA.validationMessages.PhoneNumber=Номер телефону введено не коректно
// UA.validationMessages.PositionName=Не должно содержать символов
// UA.validationMessages.SiteUrl=Повинна бути валідна URL адреса
// UA.validationMessages.Size.categoryIds=Повинно бути вибрано від {2} до {1} категорій
// UA.validationMessages.Size.documents=Не больше трьох файлів
// UA.validationMessages.Size.java.lang.String=Повинно бути не більше {1} символів
// UA.validationMessages.typeMismatch.deadline=Повинно бути в форматі 'ДД.ММ.РРРР'
// UA.validationMessages.UniqueEmail=Вказана email адреса вже занята
// UA.validationMessages.UniqueNgoName=Організація з вказаним ім'ям вже зареєстрована
// UA.validationMessages.UniquePartnerName=Партнер з вказаним ім'ям вже зареєстрований
// UA.volunteer.registration.panel.header=Реєстрація волонтера
// UA.volunteer.status.havetask=Працюю над задачею
// UA.volunteer.status.timeout=Тайм-аут
// UA.volunteer.status.withouttask=Без задачи
// UA.volunteer.status=Статус волонтера на сайті:
// UA.volunteer=Волонтер